{% set version = "0.44.0" %}

package:
  name: jedi-language-server
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jedi-language-server/jedi_language_server-{{ version }}.tar.gz
  sha256: 276536bd00e64e65753d54cd35237d62730daffd65292dc8510d3063ebaefe4d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - jedi-language-server = jedi_language_server.cli:cli

requirements:
  host:
    - pip
    - poetry-core >=1.8.0
    - python {{ python_min }}
  run:
    - docstring-to-markdown >=0.4,<1.0
    - cattrs >=23.1.2
    - jedi >=0.19.1,<0.20.0
    - lsprotocol >=2023.0.1
    - pygls >=1.1.0,<2.0.0
    - python >={{ python_min }}
    - typing_extensions >=4.5.0,<5.0.0

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - jedi_language_server
  commands:
    - pip check
    - jedi-language-server --version
    - jedi-language-server --help

about:
  home: https://github.com/pappasam/jedi-language-server
  summary: A language server for Jedi!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
