{% set version = "0.40.0" %}

package:
  name: jedi-language-server
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jedi-language-server/jedi_language_server-{{ version }}.tar.gz
  sha256: bacbae2930b6a8a0f1f284c211672fceec94b4808b0415d1c3352fa4b1ac5ad6

build:
  number: 0
  noarch: python
  entry_points:
    - jedi-language-server = jedi_language_server.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - poetry-core >=1.0.5
    - python >=3.7
  run:
    - docstring-to-markdown >=0.4,<1.0
    - importlib-metadata >=3.10.1,<4
    - jedi >=0.18.1,<0.19.0
    - lsprotocol >=2022.0.0a9
    - pydantic >=1.9.1,<2.0
    - pygls >=1.0.0,<2.0.0
    - python >=3.7

test:
  imports:
    - jedi_language_server
  commands:
    - pip check
    - jedi-language-server --version
    - jedi-language-server --help
  requires:
    - pip

about:
  home: https://github.com/pappasam/jedi-language-server
  summary: A language server for Jedi!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
