{% set name = "jedi-language-server" %}
{% set version = "0.31.1" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jedi-language-server-{{ version }}.tar.gz
  sha256: bc2312b0dda9007f739859ef33c2e4fd56540f09e296a6f49a3dc0864aca947d

build:
  number: 0
  noarch: python
  entry_points:
    - jedi-language-server = jedi_language_server.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - poetry >=1.0.5
    - python >=3.6.1
  run:
    - docstring-to-markdown >=0.4,<1.0
    - importlib-metadata
    - jedi ==0.18.0
    - pydantic >=1.7,<2
    - pygls >=0.10.3,<0.11.0
    - python >=3.6.1,<4

test:
  imports:
    - jedi_language_server
  commands:
    - pip check
    - jedi-language-server --version
    - jedi-language-server --help
  requires:
    - pip

about:
  home: https://github.com/pappasam/jedi-language-server
  summary: A language server for Jedi!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
