# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 0.44.0

package:
  name: jedi-language-server
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/j/jedi-language-server/jedi_language_server-${{ version }}.tar.gz
    sha256: 276536bd00e64e65753d54cd35237d62730daffd65292dc8510d3063ebaefe4d
    target_directory: dist
  - url: https://github.com/pappasam/jedi-language-server/archive/refs/tags/v${{ version }}.tar.gz
    sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    target_directory: src

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jedi-language-server = jedi_language_server.cli:cli

requirements:
  host:
    - pip
    - poetry-core >=1.8.0
    - python ${{ python_min }}.*
  run:
    - docstring-to-markdown >=0.4,<1.0
    - cattrs >=23.1.2
    - jedi >=0.19.1,<0.20.0
    - lsprotocol >=2023.0.1
    - pygls >=1.1.0,<2.0.0
    - python >=${{ python_min }}
    - typing_extensions >=4.5.0,<5.0.0

tests:
  - python:
      imports: jedi_language_server
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - python ${{ python_min }}
        - pytest
    script:
      - jedi-language-server --version
      - jedi-language-server --help
      - coverage run --source=jedi_language_server --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=100


about:
  summary: A language server for Jedi!
  license: MIT
  license_file: dist/LICENSE
  homepage: https://github.com/pappasam/jedi-language-server

extra:
  recipe-maintainers:
    - bollwyvl
